name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configurar Maven com credenciais do GitHub
      - name: Configure Maven
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Construir e publicar o JAR no GitHub Packages
      - name: Build with Maven and Publish JAR
        run: mvn -B package deploy

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir e publicar a imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/coinmachine:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/coinmachine:${{ github.sha }}

      # Tag e publicar como 'latest'
      - name: Tag and Push Latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/coinmachine:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/coinmachine:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/coinmachine:latest
